// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdypT-X13bdkJ9vWgQ7stK_V_Axdw8PZE',
    appId: '1:320743486086:web:8a3a93d333c7b2d4e51707',
    messagingSenderId: '320743486086',
    projectId: 'gamebuddy-app',
    authDomain: 'gamebuddy-app.firebaseapp.com',
    storageBucket: 'gamebuddy-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATUk4TmK-h6eS7iBKxPtfMOY-WmgeaYyY',
    appId: '1:320743486086:android:111b3ae9dbb7f3f2e51707',
    messagingSenderId: '320743486086',
    projectId: 'gamebuddy-app',
    storageBucket: 'gamebuddy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvhtCrD-RQgu7dibED3KfhctDd5dtrFGw',
    appId: '1:320743486086:ios:633da2b608c53696e51707',
    messagingSenderId: '320743486086',
    projectId: 'gamebuddy-app',
    storageBucket: 'gamebuddy-app.firebasestorage.app',
    iosBundleId: 'com.example.newGameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvhtCrD-RQgu7dibED3KfhctDd5dtrFGw',
    appId: '1:320743486086:ios:633da2b608c53696e51707',
    messagingSenderId: '320743486086',
    projectId: 'gamebuddy-app',
    storageBucket: 'gamebuddy-app.firebasestorage.app',
    iosBundleId: 'com.example.newGameApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdypT-X13bdkJ9vWgQ7stK_V_Axdw8PZE',
    appId: '1:320743486086:web:bf797daa53b3ea88e51707',
    messagingSenderId: '320743486086',
    projectId: 'gamebuddy-app',
    authDomain: 'gamebuddy-app.firebaseapp.com',
    storageBucket: 'gamebuddy-app.firebasestorage.app',
  );
}
